# Site settings
title: Porcelain Games Blog
email: porcelaingames@gmail.com
description: >
  Porcelain Games is a small indie team dedicated to making elegant,
  high-quality games. Check out our debut game, <a href='http://play-impulse.com'>Impulse</a>
base_url: "http://play-impulse.com/blog" # the base hostname & protocol for your site
twitter_username: markazhang

# Build settings
markdown: kramdown
