# Site settings
title: Porcelain Games Blog
email: porcelaingames@gmail.com
description: >
  Porcelain Games is a small indie team dedicated to making elegant,
  high-quality games. Check out our debut game, <a href='http://play-impulse.com'>Impulse</a>
host: "http://play-impulse.com"
baseurl: "/blog" # the base hostname & protocol for your site
twitter_username: markazhang

# Build settings
markdown: kramdown
